apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #readwritemany #read
  hostPath:
    path: "/Users/bhoopendrakumar/mnt/data"