---
apiVersion: v1
kind: Service
metadata:
  name: utilizationapi
  labels:
    app: utilizationapi
spec:
  type: NodePort
  selector: 
    app: utilizationapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilizationapi
spec:
  selector: 
    matchLabels:
      app: utilizationapi
  replicas: 1
  template: 
    metadata:
      labels:
        app: utilizationapi
    spec:
      containers:
      - name: utilizationapi
        image: bhoopendra/tracker:1.0.2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /utilization/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 1
