---
apiVersion: v1
kind: Service
metadata:
  name: utilizationui
  labels:
    app: utilizationui
spec:
  type: LoadBalancer
  selector: 
    app: utilizationui
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilizationui
spec:
  selector: 
    matchLabels:
      app: utilizationui
  replicas: 1
  template: 
    metadata:
      labels:
        app: utilizationui
    spec:
      containers:
      - name: utilizationui
        image: bhoopendra/tracker-ui:1.0.1
        env:
          - name: REACT_APP_GATEWAY_URL
            value: http://utilizationapi:8080/utilization
        ports:
        - containerPort: 80
